verbose = "warn"
no_progress = true
include_mail = false
max_retries = 2
retry_wait_time = 2
timeout = 20
root_dir = "output"

exclude = [
  "https://orcid.org/0000-0002-0037-9394",
  "https://instagram.com/i.rracionalx",
  "https://www.instagram.com/i.rracionalx",
  "https://getpelican.com/",
  "https://www.python.org/",
  "https://alejandroucanpuc.github.io/",
  "https://alejandroucanpuc.github.io/es/",
  "https://alejandroucanpuc.github.io/theme/css/main.css",
  "https://alejandroucanpuc.github.io/feeds/all.atom.xml",
]